### ISSUE TITLE
F1103 20:53:52.339550 156870 io.cpp:63] Check failed: fd != -1 (-1 vs. -1) File not found: ../models/VOC300TRAINED_4e04e3.caffemodel

### ISSUE THREAD

**Issue by taomrzhang** [bairdzhang/des#1]
I1103 20:53:52.332732 156870 net.cpp:283] Network initialization done.
I1103 20:53:52.333328 156870 solver.cpp:75] Solver scaffolding done.
I1103 20:53:52.339506 156870 caffe.cpp:155] Finetuning from ../models/VOC300TRAINED_4e04e3.caffemodel
F1103 20:53:52.339550 156870 io.cpp:63] Check failed: fd != -1 (-1 vs. -1) File not found: ../models/VOC300TRAINED_4e04e3.caffemodel
*** Check failure stack trace: ***
    @     0x7f7dbc74e5cd  google::LogMessage::Fail()
    @     0x7f7dbc750433  google::LogMessage::SendToLog()
    @     0x7f7dbc74e15b  google::LogMessage::Flush()
    @     0x7f7dbc750e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7dbce43d3c  caffe::ReadProtoFromBinaryFile()
    @     0x7f7dbce281a6  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f7dbd066c3a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f7dbd066cde  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40a849  CopyLayers()
    @           0x40bca4  train()
    @           0x4077c8  main
    @     0x7f7dbaee4830  __libc_start_main
    @           0x408099  _start
    @              (nil)  (unknown)
Aborted (core dumped)
hello , when i run the  sudo ./jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh, i met that error, how can i solve it? thank you

**Comment by bairdzhang** [comment]
Hi, please download the pre-trained model https://github.com/bairdzhang/des/blob/des/initial_models/VOC300TRAINED_4e04e3.caffemodel and change the --weights= option in DES300x300.sh to specify that pre-trained model.

**Comment by taomrzhang** [comment]
> Hi, please download the pre-trained model https://github.com/bairdzhang/des/blob/des/initial_models/VOC300TRAINED_4e04e3.caffemodel and change the --weights= option in DES300x300.sh to specify that pre-trained model.

I am sorry I can not solve it. when I put 'VOC300TRAINED_4e04e3.caffemodel' in ../models or ../models/VGGNet, I met the same error again. and in DES300*300.sh the --weights="../models/VOC300TRAINED_4e04e3.caffemodel" \ 
thank you

**Comment by bairdzhang** [comment]
In jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh, it first enter the root folder of this repo (/workspace/release/caffe-ssd as the example shell script), and run ./build/tools/caffe with the pre-trained model ../models/VOC300TRAINED_4e04e3.caffemodel.
I guess the path (../models/VOC300TRAINED_4e04e3.caffemodel) is based on the current work folder, which is /workspace/release/caffe-ssd, so the pre-trained model should be located in /workspace/release/model/VOC300TRAINED_4e04e3.caffemodel.

A safe way is to try the absolute path of the pre-trained model in the shell script.

**Comment by taomrzhang** [comment]
> In jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh, it first enter the root folder of this repo (/workspace/release/caffe-ssd as the example shell script), and run ./build/tools/caffe with the pre-trained model ../models/VOC300TRAINED_4e04e3.caffemodel.
> I guess the path (../models/VOC300TRAINED_4e04e3.caffemodel) is based on the current work folder, which is /workspace/release/caffe-ssd, so the pre-trained model should be located in /workspace/release/model/VOC300TRAINED_4e04e3.caffemodel.
> 
> A safe way is to try the absolute path of the pre-trained model in the shell script.

thank you very much. I have solved it in that way.
