### ISSUE TITLE
./jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh

### ISSUE THREAD

**Issue by taomrzhang** [bairdzhang/des#2]
tee: jobs/VGGNet/VOC0712/DES300x300/DES300x300.log: 没有那个文件或目录
./jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh: 行 2: ./build/tools/caffe: 没有那个文件或目录
when I run ./jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh, I met that error, but the DES300x300.log is existed here. how can I solve it? thank you.

**Comment by bairdzhang** [comment]
You will need to modify the first line in ./jobs/VGGNet/VOC0712/DES300x300/DES300x300.sh, to cd into the root folder (where you can find the file ./build/tools/caffe) of this GitHub repo. Sorry for the confusion!
