### ISSUE TITLE
caffe: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

### ISSUE THREAD

**Issue by taomrzhang** [bairdzhang/des#3]
caffe: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
*** Aborted at 1541466730 (unix time) try "date -d @1541466730" if you are using GNU date ***
PC: @     0x7efda65ed428 gsignal
*** SIGABRT (@0x12f3) received by PID 4851 (TID 0x7efcfb5ff700) from PID 4851; stack trace: ***
    @     0x7efda65ed4b0 (unknown)
    @     0x7efda65ed428 gsignal
    @     0x7efda65ef02a abort
    @     0x7efda66352e8 (unknown)
    @     0x7efda6639426 (unknown)
    @     0x7efda663a743 (unknown)
    @     0x7efda663c184 __libc_malloc
    @     0x7efd9df9cd42 cv::fastMalloc()
    @     0x7efd9e06daf1 cv::Mat::create()
    @     0x7efd9e090998 cv::_OutputArray::create()
    @     0x7efd9e114964 cv::split()
    @     0x7efda8769553 caffe::DataTransformer<>::ExpandImage()
    @     0x7efda8769d14 caffe::DataTransformer<>::ExpandImage()
    @     0x7efda8774c09 caffe::DataTransformer<>::ExpandImage()
    @     0x7efda85ed8fa caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7efda85c2abf caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7efda8725585 caffe::InternalThread::entry()
    @     0x7efd9b7185d5 (unknown)
    @     0x7efd93ee56ba start_thread
    @     0x7efda66bf41d clone
    @                0x0 (unknown)
I1106 09:12:12.081128  4851 blocking_queue.cpp:50] Data layer prefetch queue empty
HI, I am sorry, after the Iteration=1080,I met that error. Is it out of merrory? My gpu is GTX1080, and there are two gpus in my computer. I can not find the correct answer on the Internet.  How can I solve it? thank you.

**Comment by bairdzhang** [comment]
Looks like it is an error occurred at data pre-processing (https://github.com/bairdzhang/des/blob/des/src/caffe/data_transformer.cpp#L876). Are you running on VOC or COCO? Or you are running on your dataset?

**Comment by taomrzhang** [comment]
> Looks like it is an error occurred at data pre-processing (https://github.com/bairdzhang/des/blob/des/src/caffe/data_transformer.cpp#L876). Are you running on VOC or COCO? Or you are running on your dataset?

I am running on VOC and COCO. should I modify the data_transformer.cpp? How can I solve it?

**Comment by bairdzhang** [comment]
Does that happen immediately or after some iterations? I guess we shall not change data_transformer.cpp. You can try to verify the lmdb file; if the lmdb file looks correct, we can set a breakpoint right before the cv::split function to see what are the inputs to it.

**Comment by FantasyJXF** [comment]
I'm running the caffe-ssd on VOC0712, the problem happens after hundreds of iterations.

How did you fixed the bug?

**Comment by ZhenpengChenCode** [comment]
Hi, the problem happens when I run on my own dataset. Can you tell me how did you fix the bug?
